image: williamyeh/ansible:centos7

variables:
  DOCKER_HOST: unix:///var/run/docker.sock

stages:
  - check
  - deploy

#before_script:
#  - chmod 640 /builds/ && chmod 640 /builds/alltel24/ && chmod 640 /builds/alltel24/admin/ && chmod 640 /builds/alltel24/admin/infrastructure
#  - echo $PASS > .pass && chmod 600 .pass

#ping_asterisk_hosts:
#  stage: check
#  script:
#    - ansible -m ping asterisk
#  tags:
#    - ansible

create_users_check:
  stage: check
  script:
    - ansible-playbook users.yml -C -D -i hosts
  when: manual
  tags:
    - users

create_users:
  stage: deploy
  script:
    - ansible-playbook users.yml -D -i hosts
  tags:
    - users
