image: williamyeh/ansible:centos7

variables:
  DOCKER_HOST: unix:///var/run/docker.sock

stages:
  - deploy

#https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
# in my gitlab-ce 12.9.2-ce.0 I have to do this "crutch"
before_script:
  - chmod 640 /builds/ && chmod 640 /builds/test/ && chmod 640 /builds/test/test_users/

create_users:
  stage: deploy
  script:
    - ansible-playbook users.yml -D -i hosts
  when: manual
  tags:
    - users
