image: williamyeh/ansible:centos7

variables:
  DOCKER_HOST: unix:///var/run/docker.sock

stages:
  - check
  - deploy

create_users_check:
  stage: check
  script:
    - ansible-playbook users.yml -C -D -i hosts
  tags:
    - users

create_users:
  stage: deploy
  script:
    - ansible-playbook users.yml -D -i hosts
  when: manual
  tags:
    - users
